### ISSUE TITLE
API - User list

### ISSUE THREAD

**Issue by aliceout** [Watizat/web_app#150]
Liste des utilisateur·ice·s avec adresse mail, libremene taccessible sur l'API, via ! https://watizat.lunalink.nl/users

**Comment by LauraBrizard** [comment]
Il faut vérifier les droits dans Directus, on les a peut être ouverts pour faire les test sur le BO ?

**Comment by aliceout** [comment]
La dame @LauraBrizard l'avait raison !
J'ai modifié les droits d'accès pour "Public", ça à l'air de fonctionner !
Merci 😚
